routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::redirect('/', 'home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('application', 'ApplicationController');
Route::post('application/getstate', 'ApplicationController@getstate')->name('application.getstate');
Route::post('application/status', 'ApplicationController@status')->name('application.status');
Route::get('register/pass', 'Auth\RegisterController@resetpass')->name('register.pass');
Route::put('register/reset', 'Auth\RegisterController@reset')->name('register.reset');
Route::get('profilesetting', 'ApplicationController@profilesetting')->name('application.profilesetting');
Route::put('updateprofile', 'ApplicationController@updateprofile')->name('application.updateprofile');

resources/views/application-edit.blade.php
 @extends('layouts.master')

@section('content')
<div class="content-wrapper">

  <div class="content-heading">
   <span><i class="fa fa-file"></i> Submit your application</span>
 </div>

 <div class="panel panel-default">
   <div class="panel-body">
    <form class="form-horizontal" action="{{ route('application.update',['id'=>$application->id]) }}" method="post" id="form" enctype="multipart/form-data">
    @csrf
     @method('PUT')
     <div class="form-group">
       <div class="col-sm-6">
         <label class="control-label">
          First name
        </label>
        <input type="text" name="first_name" class="form-control" placeholder="First name" value="{{$application->first_name}}">
      </div>
      <div class="col-sm-6">
       <label class="control-label">
         Last name
       </label>
       <input type="text" name="last_name" class="form-control" placeholder="Last name" value="{{$application->last_name}}">
     </div>
   </div>
     <div class="form-group">
     <div class="col-sm-6">
       <label class="control-label">
        Father Name
      </label>
      <input type="text" name="father_name" class="form-control" placeholder="Father Name" value="{{$application->father_name}}">
    </div>
  
  
    <div class="col-sm-6">
       <label class="control-label">
        Phone number
      </label>
      <input type="number" name="phone" class="form-control" placeholder="Phone number" value="{{$application->phone}}">
    </div>
    </div>
    <div class="form-group">
    <div class="col-sm-6">
     <label class="control-label">
      Email
    </label>
    <input type="text" name="email" class="form-control" placeholder="Email" value="{{$application->email}}">
  </div>
  <div class="col-sm-6">
   <label class="control-label">
    Address
  </label>
  <input type="text" name="address" class="form-control" placeholder="Address HouseNo landmark" value={{$application->address}}>
</div>

</div>

<div class="form-group">
 <div class="col-sm-6">
   <label class="control-label">
     Select city
   </label>
   
     <select class="form-control select2-4" name="city_id" id="city_id">
       <option value="">Select</option>
       @foreach($city as $cit)
         <option value="{{ $cit->id }}" {{ ($application->city_id == $cit->id) ? 'selected' : '' }}>{{ $cit->name }}</option>
         @endforeach
      </select>
 </div>
 <div class="col-sm-6">
   <label class="control-label">
    State
  </label>
   <input type="text"  class="form-control" placeholder="state" name="state_id" id="state_id" value="{{$application->city->state->name}}">
</div>
</div>
<div class="form-group">
<div class="col-sm-6">
 <label class="control-label">
  Country
</label>
   <input type="text"  class="form-control" placeholder="Country" name="country_id" id="country_id" value="{{$application->city->state->country->name}}">
  

</div>

  <div class="col-sm-6">
   <label class="control-label"> Upload Documents </label>
   {{-- <input type="file" name="documents[]" class="form-control filestyle"  onChange="readURL(this);"> --}}
   <input type="file" name="documents[]" class="form-control filestyle" onchange="preview_images();" multiple/>
 </div>
</div>
 <div class="row">
      
      @foreach(json_decode($application->documents) as $row)
        <div class="col-sm-2">
          <div class="file-icon-c2 text-center">  
                 
            <div class="boxdus">
              <i class="fa fa-file-text-o"></i>

              @php
                $fileArr = explode('/', $row);
              @endphp

              <p>{{ $fileArr[count($fileArr)-1] }} <br><span></span></p>
            </div>
            <div class="row rowcmc">
            <div class="col-sm-12 footerlist-attach">
              <a href="{{ asset($row) }}" title="Download">
                <i class="fa fa-cloud-download"></i></a>
              
              <a href="{{ asset($row) }}" title="View" target="_blank"><i class="fa fa-search-plus"></i></a>
           
          </div>
          </div>
          </div>
        </div>
      @endforeach
      
      </div>
  
<div class="form-group">
 <div class="col-sm-12">
  <div class="pull-right">
   <button class="btn btn-info btn-lg" type="submit">Submit</button>
 </div>
</div>
</div>
</form>

</div>
</div>
</div>
@endsection

@section('custom_css')
  <style>
    .form-group {
      padding: 0 15px;
    }


  </style>
@endsection

@section('custom_js')
  <script src="{{ asset('js/input-values.jquery.js') }}"></script>
  <script src="{{ asset('js/bootstrap-filestyle.js') }}"></script>
 
 <script type="text/javascript">
   $('#city_id').change(function() {
     var city =$(this).val();
     // alert(city);
        var formData = new FormData();
        formData.append('city',city);
        formData.append("_token", '{{ csrf_token() }}');
     $.ajax({
       url:'{{ route('application.getstate') }}',
       type: 'POST',
       dataType: 'json',
       data:formData,
       processData: false,
       contentType: false
     })
     
     .done(function(data) {
       if(data.status=="success")
       {
      alert(data.state.id);

         $("#state_id").val(data.state.name);
         $("#country_id").val(data.country.name);
             
       }
       else
       {
         $("#state_id").val();
         $("#country_id").val();
       }
    
     });

    });


function preview_images() 
{
 var total_file=document.getElementById("images").files.length;
 for(var i=0;i<total_file;i++)
 {
  $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='"+URL.createObjectURL(event.target.files[i])+"'></div>");
 }
}

 </script>
@component('components.form-submit')
      @slot('form')
          form
      @endslot

      @slot('redirect')
        {{ route('application.index') }}
      @endslot
  @endcomponent
@endsection

resources/views/application.blade.php
 @extends('layouts.master')

@section('content')
<div class="content-wrapper">

  <div class="content-heading">
   <span><i class="fa fa-file"></i> Submit your application</span>
 </div>

 <div class="panel panel-default">
   <div class="panel-body">
    <form class="form-horizontal" action="{{ route('application.store') }}" method="post" id="form" enctype="multipart/form-data">
    @csrf
     <div class="form-group">
       <div class="col-sm-6">
         <label class="control-label">
          First name
        </label>
        <input type="text" name="first_name" class="form-control" placeholder="First name">
      </div>
      <div class="col-sm-6">
       <label class="control-label">
         Last name
       </label>
       <input type="text" name="last_name" class="form-control" placeholder="Last name">
     </div>
   </div>
     <div class="form-group">
     <div class="col-sm-6">
       <label class="control-label">
        Father Name
      </label>
      <input type="text" name="father_name" class="form-control" placeholder="Father Name">
    </div>
  
  
    <div class="col-sm-6">
       <label class="control-label">
        Phone number
      </label>
      <input type="number" name="phone" class="form-control" placeholder="Phone number">
    </div>
    </div>
    <div class="form-group">
    <div class="col-sm-6">
     <label class="control-label">
      Email
    </label>
    <input type="text" name="email" class="form-control" placeholder="Email">
  </div>
  <div class="col-sm-6">
   <label class="control-label">
    Address
  </label>
  <input type="text" name="address" class="form-control" placeholder="Address HouseNo landmark">
</div>

</div>

<div class="form-group">
 <div class="col-sm-6">
   <label class="control-label">
     Select city
   </label>
   
     <select class="form-control select2-4" name="city_id" id="city_id">
       <option value="">Select</option>
       @foreach($city as $cit)
         <option value="{{$cit->id}}">{{$cit->name}}</option>
         @endforeach
      </select>
 </div>
 <div class="col-sm-6">
   <label class="control-label">
    State
  </label>
   <input type="text"  class="form-control" placeholder="state" name="state_id" id="state_id">
</div>
</div>
<div class="form-group">
<div class="col-sm-6">
 <label class="control-label">
  Country
</label>
   <input type="text"  class="form-control" placeholder="Country" name="country_id" id="country_id">
  

</div>

  <div class="col-sm-6">
   <label class="control-label"> Upload Documents </label>
   {{-- <input type="file" name="documents[]" class="form-control filestyle"  onChange="readURL(this);"> --}}
   <input type="file" name="documents[]" class="form-control filestyle" onchange="preview_images();" multiple/>
 </div>
</div>
  
<div class="form-group">
 <div class="col-sm-12">
  <div class="pull-right">
   <button class="btn btn-info btn-lg" type="submit">Submit</button>
 </div>
</div>
</div>
</form>

</div>
</div>
</div>
@endsection

@section('custom_css')
  <style>
    .form-group {
      padding: 0 15px;
    }


  </style>
@endsection

@section('custom_js')
  <script src="{{ asset('js/input-values.jquery.js') }}"></script>
  <script src="{{ asset('js/bootstrap-filestyle.js') }}"></script>
 
 <script type="text/javascript">
   $('#city_id').change(function() {
     var city =$(this).val();
     // alert(city);
        var formData = new FormData();
        formData.append('city',city);
        formData.append("_token", '{{ csrf_token() }}');
     $.ajax({
       url:'{{ route('application.getstate') }}',
       type: 'POST',
       dataType: 'json',
       data:formData,
       processData: false,
       contentType: false
     })
     
     .done(function(data) {
       if(data.status=="success")
       {
      

         $("#state_id").val(data.state.name);
         $("#country_id").val(data.country.name);
             
       }
       else
       {
         $("#state_id").val();
         $("#country_id").val();
       }
    
     });

    });


function preview_images() 
{
 var total_file=document.getElementById("images").files.length;
 for(var i=0;i<total_file;i++)
 {
  $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='"+URL.createObjectURL(event.target.files[i])+"'></div>");
 }
}

 </script>
@component('components.form-submit')
      @slot('form')
          form
      @endslot

      @slot('redirect')
        {{ route('application.index') }}
      @endslot
  @endcomponent
@endsection

resources/views/home.blade.php
 @extends('layouts.master')

@section('content')
<div class="content-wrapper">
  <div class="content-heading">
     <span><em class="fa fa-file-text-o"></em>  </span> 
    
  </div>

  <div class="panel panel-default">
     <div class="panel-body">
      <ul class="nav nav-tabs">
     
        <li  class="active" ><a data-toggle="tab" href="#tabform">Dashboard </a></li>
     
      </ul>

      <div class="tab-content">
      
        <div id="tabform" class="tab-pane fade  in active ">

           <div class="container d-flex justify-content-center padding">
            @if(Auth::user()->level=='1')
    <div class="row">
        <div class="col-sm-4">
            <div class="progress blue"> <span class="progress-left"> <span class="progress-bar"></span> </span> <span class="progress-right"> <span class="progress-bar"></span> </span>
                <div class="progress-value">{{count($approved)}}</div>
              </div>
                <span class="align-text-center" style="text-align:center; position: absolute; right: 2%;
    left: 2%">Approved</span>
        
            </div>
       
         <div class="col-sm-4">
            <div class="progress red" > <span class="progress-left"> <span class="progress-bar"></span> </span> <span class="progress-right" > <span class="progress-bar"></span> </span>
                <div class="progress-value" style="border-color: #36ff04";>{{count($rejected)}}</div>
            </div>
            <span class="align-text-center" style="text-align:center; position: absolute; right: 2%;
    left: 2%">Rejected</span>
        
        </div>
         <div class="col-sm-4">
            <div class="progress green"> <span class="progress-left"> <span class="progress-bar"></span> </span> <span class="progress-right"> <span class="progress-bar"></span> </span>
                <div class="progress-value">{{count($pending)}}</div>
            </div>
            
        <span class="align-text-center" style="text-align:center; position: absolute; right: 2%;
    left: 2%">Pending</span>
        </div>
        @else
         <span class="align-text-center" style="text-align:center; position: absolute; right: 2%;
    left: 2%; font-color:red;font-size: x-large;  ">Welcome please fill your Application</span>
        
        @endif
    </div>
</div>

        </div>
      
      </div>
     </div>
  </div>
</div>
@endsection

@section('custom_css')
  <style>
    .form-group {
      padding: 0 15px;
    }


  </style>
@endsection

@section('custom_js')
  <script src="{{ asset('js/input-values.jquery.js') }}"></script>
  <script src="{{ asset('js/bootstrap-filestyle.js') }}"></script>
 

@endsection

resources/views/settings.blade.php
@extends('layouts.master')
@section('content')
<div class="content-wrapper">

  <div class="content-heading">
   <span><i class="fa fa-user"></i> Profile Settings</span>
 </div>

 <div class="panel panel-default">
   <div class="panel-body">
    <form class="form-horizontal" action="{{ route('application.updateprofile') }}" method="post" id="form" enctype="multipart/form-data">
    @csrf
    @method('PUT')
     <div class="form-group">
       <div class="col-sm-4">
         <label class="control-label">
          First name
        </label>
        <input type="text" name="first_name" class="form-control" placeholder="First name" value="{{Auth::user()->first_name}}">
      </div>
      <div class="col-sm-4">
       <label class="control-label">
         Last name
       </label>
       <input type="text" name="last_name" class="form-control" placeholder="Last name" value="{{Auth::user()->last_name}}">
     </div>
     <div class="col-sm-4">
     <label class="control-label">
      Email
    </label>
    <input type="text" name="email" class="form-control" placeholder="Email" value="{{Auth::user()->email}}">
  </div>
   </div>
     
  
  
   
    <div class="form-group">
    
  <div class="col-sm-3">
     <label class="control-label">
      Password
    </label>
    <input type="password" name="password" class="form-control" placeholder="Password" value="">
  </div>
 <div class="col-sm-3">
     <label class="control-label">
     confirm Password
    </label>
    <input type="password" name="password_confirmation" class="form-control" placeholder="Password" value="">
  </div>

  <div class="col-sm-3">
   <label class="control-label"> Upload profile picture </label>
   {{-- <input type="file" name="documents[]" class="form-control filestyle"  onChange="readURL(this);"> --}}
   <input type="file" name="image" class="form-control filestyle"  onChange="readURL(this);" >
 <div>
 </div class="col-sm-3">
   <div class="imgbox-photo">
    <span class="helper"></span>
  <img src="@if(file_exists(Auth::user()->image)) {{ asset(Auth::user()->image) }} @else {{ asset(Auth::user()->image) }} @endif" alt="" class="previmg" id="blah">
  
  </div>
 </div>
</div>
  
<div class="form-group">
 <div class="col-sm-12">
  <div class="pull-right">
   <button class="btn btn-info btn-lg" type="submit">Submit</button>
 </div>
</div>
</div>
</form>

</div>
</div>
</div>
@endsection

@section('custom_css')
  <style>
    .form-group {
      padding: 0 15px;
    }


  </style>
@endsection

@section('custom_js')
  <script src="{{ asset('js/input-values.jquery.js') }}"></script>
  <script src="{{ asset('js/bootstrap-filestyle.js') }}"></script>
 
 <script type="text/javascript">
   $('#city_id').change(function() {
     var city =$(this).val();
     // alert(city);
        var formData = new FormData();
        formData.append('city',city);
        formData.append("_token", '{{ csrf_token() }}');
     $.ajax({
       url:'{{ route('application.getstate') }}',
       type: 'POST',
       dataType: 'json',
       data:formData,
       processData: false,
       contentType: false
     })
     
     .done(function(data) {
       if(data.status=="success")
       {
      alert(data.state.id);

         $("#state_id").val(data.state.name);
         $("#country_id").val(data.country.name);
             
       }
       else
       {
         $("#state_id").val();
         $("#country_id").val();
       }
    
     });

    });




 </script>
@component('components.form-submit')
      @slot('form')
          form
      @endslot

      @slot('redirect')
        {{ route('application.index') }}
      @endslot
  @endcomponent
@endsection

resources/views/view-application.blade.php
 @extends('layouts.master')

@section('content')
<div class="content-wrapper">

  <div class="content-heading">
   <span><i class="fa fa-file"></i> View application</span>
 </div>

 <div class="panel panel-default">
   <div class="panel-body">

@if(Auth::user()->level=='3')
    <div class="row">
     <div class="col-lg-12" style="height: 100%;">
        <span class="align-text-center" style="text-align:center; position: absolute; right: 2%;
    left: 2%; font-size: x-large; top:5%; bottom:5%; ">Thank your for your Application</span>
     </div>
    <br>
    </div>
@else
    <div class="table-responsive">
      <table class="datatable table table-striped table-hover">
       <thead>
        <tr>
         <th>#</th>
         <th>First name</th>
         <th>Last name</th>
         <th>Phone</th>
         <th>Email</th>
         <th>city</th>
        
         <th style="min-width: 100px;">Action</th>
       </tr>
     </thead>
     <tbody>
      @foreach($applicationlist as $row)
      <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $row->first_name }}</td>
        <td>{{ $row->last_name }}</td>
        <td>{{ $row->phone }}</td>
        <td>{{ $row->email }}</td>
        <td>{{ $row->city->name }}</td>
        

        <td>
          <a href="{{ route('application.edit',['id'=>$row->id]) }}" class="btn btn-info btn-xs">Edit</a>
         
          {{-- <button class="btn btn-xs {{ ($row->status==1) ? 'btn-success' : 'btn-danger' }}" rel1="{{ $row->status }}" rel2="{{ $row->id }}" onclick="changeStatus(this);">{{ ($row->status==1) ? 'Active' : 'Inactive' }}</button> --}}

          <button class="btn btn-xs @if($row->status==1) btn-success @elseif($row->status==2) btn-info @else btn-danger @endif" rel1="{{ $row->status }}" rel2="{{ $row->id }}" onclick="changeStatus(this);">@if($row->status==1) pending @elseif($row->status==2) Approved @else Rejected @endif </button>
          <form action="{{ route('application.status') }}" method="post" id="form-status{{ $row->id }}" style="display: none;">
          @csrf
          @method('put')
          <input type="hidden" name="id" value="{{ $row->id }}">
          <input type="hidden" name="email" value="{{ $row->email }}">
          <input type="hidden" name="status" value="{{ $row->status }}">
          <button class="btn btn-danger" type="submit">Status</button>
          </form>
          
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>
</div>
@endif


</div>
</div>
</div>
@endsection

@section('custom_css')
  <style>
    .form-group {
      padding: 0 15px;
    }


  </style>
@endsection

@section('custom_js')
  <script src="{{ asset('js/input-values.jquery.js') }}"></script>
  <script src="{{ asset('js/bootstrap-filestyle.js') }}"></script>
 
 <script>
  function changeStatus(ele) {
    var status = $(ele).attr('rel1');
    var id = $(ele).attr('rel2');
    
    sweetAlert({
      title: "Are you sure?",
      /*text: "You will not be able to recover this banner!",*/
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Yes",
      cancelButtonText: "No",
      closeOnConfirm: true,
      closeOnCancel: false
    },
    function(isConfirm){
      if (isConfirm) {
        $.ajax({
          url: '{{ route('application.status') }}',
          type: 'POST',
          data: {id:id,status:status,_token:'{{ csrf_token() }}'}, 
          dataType: 'json',      
          success: function(msg)
          {
            $(ele).attr('rel1',msg.status);
            if(msg.status == 1){
              $(ele).addClass('btn-success');
              $(ele).removeClass('btn-warning');
              $(ele).removeClass('btn-info');
              $(ele).text('Pending');
            }
            elseif(msg.status==2)
            {
              $(ele).removeClass('btn-success');
              $(ele).addClass('btn-warning');
              $(ele).removeClass('btn-info');
              $(ele).text('Approved');
            }
            {
              $(ele).addClass('btn-info');
              $(ele).removeClass('btn-warning');
              $(ele).removeClass('btn-success');
              $(ele).text('Rejected');
            }
          }
        });
      } else {
          sweetAlert('Cancelled!', "", "success");
      }
    });
  }

</script>
 

@endsection